#!/usr/bin/env zsh

# Dotfiles
alias dots='git --git-dir=$HOME/.dots.git/ --work-tree=$HOME'
alias lgd='lazygit --git-dir=$HOME/.dots.git/ --work-tree=$HOME'

# Anaconda
alias ana="source /opt/miniconda3/bin/activate"
alias dana="conda deactivate"

# C-L doesn't work in tmux. This is almost as fast.
alias c="clear"

# Fasd
alias e="f -e $EDITOR"
alias m="f -e mpv"
alias o="f -e xdg-open"

alias nvim="TERM=tmux-256color nvim"

function cv() { python -m venv $HOME/doc/venv/$1 }
function av() { source $HOME/doc/venv/$1/bin/activate }
function dv() { source $HOME/doc/venv/$1/bin/deactivate }
function lv() { ls $HOME/doc/venv/ }
