#!/usr/bin/env zsh

# Dotfiles
alias dots='git --git-dir=$HOME/.dots.git/ --work-tree=$HOME'

# Anaconda
alias ana="source /opt/miniconda3/bin/activate"
alias dana="conda deactivate"

# C-L doesn't work in tmux. This is almost as fast.
alias c="clear"

# Fasd
alias e="f -e $EDITOR"
alias m="f -e mpv"
alias o="f -e xdg-open"

alias em="TERM=xterm-256color emacs -nw"
alias nvim="TERM=xterm-256color nvim"
