#! /bin/bash

hsetroot -cover "/home/yack/usr/pic/wall.png" &
sxhkd -c ~/.config/sxhkd/sxhkdrc.laptop &
mpdscribble
wal -R
dunst -conf ~/.cache/wal/dunstrc &
polybar laptop &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config bottom_margin 4
bspc config left_margin 4
bspc config right_margin 4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color #666666
bspc config focused_border_color #c9d05c
bspc config presel_feedback_color #666666

bspc config 

bspc rule -a MARS desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
