#! /bin/bash

# Remove all previous rules since we might be refreshing bspwm.
bspc rule -r "*"

hsetroot -cover "/home/yack/usr/pic/theme/bg.jpg" &
mpdscribble
setxkbmap -option ctrl:nocaps
dunst -conf ~/.config/dunst/dunstrc &

# calendar notifications
if [ -x /usr/bin/gcalcli ]; then
	while true; do
		/usr/bin/gcalcli remind 10
		sleep 300
	done &
fi

# if on PC
if [ ! -z "$(echo `xrandr` | grep -o HDMI-2)" ]; then
	polybar desktop &
	sxhkd -c ~/.config/sxhkd/sxhkdrc.desk &
else
	polybar laptop &
	sxhkd -c ~/.config/sxhkd/sxhkdrc.laptop &
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2

bspc config bottom_margin 4
bspc config left_margin 4
bspc config right_margin 4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color #666666
bspc config focused_border_color #c9d05c
bspc config presel_feedback_color #666666

bspc rule -a MARS desktop='^3' # MIPS programming yeep
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv desktop='^8' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a "*doom* - Doom Emacs" desktop="^2" state=tiling
