#! /bin/bash

# Remove all previous rules since we might be refreshing bspwm.
bspc rule -r "*"

wmname LG3D
xrdb -merge ~/.Xresources
dunst -conf ~/.config/dunst/dunstrc &
urxvtd -q -f -o
mpd_discord_richpresence &
aw-server &

if xrandr | grep -q "eDP-1"; then
    sxhkd -c ~/.config/sxhkd/sxhkdrc.laptop &
    polybar laptop &
    hsetroot -cover "~/usr/pic/wal/beach.jpg" &
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
else
    sxhkd -c ~/.config/sxhkd/sxhkdrc.desk &
    polybar desktop &
    if xrandr | grep -q "HDMI-1"; then
        bspc monitor ^1 -d 1 2 3 4 5
        bspc monitor ^2 -d 6 7 8 9 10
        xrandr --output HDMI-1 --primary --auto --output HDMI-2 --auto --right-of HDMI-1
        polybar desktop2 &
    else
        bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    fi
    hsetroot -cover "/hdd/pic/walls/dark/tmrw_mnt.png" &
fi


bspc config border_width 2

bspc config bottom_margin 4
bspc config left_margin 4
bspc config right_margin 4

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config ignore_ewmh_focus true

bspc config normal_border_color   #666666
bspc config focused_border_color  #c9d05c
bspc config presel_feedback_color #666666

bspc rule -a MARS desktop='^3' # MIPS programming yeep
bspc rule -a Gimp desktop='^8' state=tiling follow=on
bspc rule -a "*doom* - Doom Emacs" desktop="^2" state=tiling
bspc rule -a InputOutput state=floating
